// This file is auto-generated by FlutterFire CLI.
// You need to run: flutterfire configure
// To generate the actual configuration for your Firebase project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRn814INliD8_NVnj396GcdSm_mCJVpHM',
    appId: '1:823744797822:android:41b5316eb3a0c57ff08c2f',
    messagingSenderId: '823744797822',
    projectId: 'historyapp-d1d66',
    authDomain: 'historyapp-d1d66.firebaseapp.com',
    storageBucket: 'historyapp-d1d66.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRn814INliD8_NVnj396GcdSm_mCJVpHM',
    appId: '1:823744797822:android:41b5316eb3a0c57ff08c2f',
    messagingSenderId: '823744797822',
    projectId: 'historyapp-d1d66',
    storageBucket: 'historyapp-d1d66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRn814INliD8_NVnj396GcdSm_mCJVpHM',
    appId: '1:823744797822:android:41b5316eb3a0c57ff08c2f',
    messagingSenderId: '823744797822',
    projectId: 'historyapp-d1d66',
    storageBucket: 'historyapp-d1d66.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRn814INliD8_NVnj396GcdSm_mCJVpHM',
    appId: '1:823744797822:android:41b5316eb3a0c57ff08c2f',
    messagingSenderId: '823744797822',
    projectId: 'historyapp-d1d66',
    storageBucket: 'historyapp-d1d66.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );
}
